name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: "0 3 * * *"   # daily at 3:00 AM UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          save_min_runs_number: 3  # Keep only latest 3 runs
          dry: false
