name: Build and Run NaukriProfileUpdater

on:
  schedule:
    - cron: "30 2 * * *"
    - cron: "30 14 * * *" 
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x seleniumRevision/gradlew

      - name: Run Gradle build
        working-directory: seleniumRevision
        run: ./gradlew clean build

      - name: Execute NaukriProfileUpdater
        working-directory: seleniumRevision
        run: ./gradlew run --args='naukri.NaukriProfileUpdater'
