name: Build and Run NaukriProfileUpdater

on:
  schedule:
    # 8:00 AM IST = 2:30 AM UTC
    - cron: "30 2 * * *"
    # 8:00 PM IST = 2:30 PM UTC
    - cron: "30 14 * * *"
  workflow_dispatch: # manual trigger button

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21 (latest LTS)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Upgrade system packages
        run: |
          sudo apt-get update
          sudo apt-get -y upgrade

      - name: Install Google Chrome
        run: |
          sudo apt-get install -y google-chrome-stable

      - name: Make gradlew executable
        run: chmod +x seleniumRevision/gradlew

      - name: Upgrade Gradle wrapper
        working-directory: seleniumRevision
        run: ./gradlew wrapper --gradle-version 8.10.2 --distribution-type all

      - name: Build with Gradle
        working-directory: seleniumRevision
        run: ./gradlew clean build --stacktrace

      - name: Run NaukriProfileUpdater
        working-directory: seleniumRevision
        run: ./gradlew run --args='naukri.NaukriProfileUpdater'
